<?php

//$form = $this->form;
//$form->setAttribute('action', $this->url('album', array('action' => 'add')));
//$form->prepare();
//echo $this->form()->openTag($form);

?>

<div class="container" style="margin-top: 5%;">
    <div class="col-md-6 col-md-offset-3">

        <!-- Search Form -->
        <form role="form" method="post" action="/">
        
        <!-- Search Field -->
            <div class="row">
                <h1 class="text-center"><?php echo $title; ?></h1>
                <div class="form-group">
                    
                    <div class="input-group">
                        <input class="form-control" type="text" name="searchText" placeholder="Search" required/>
                        <span class="input-group-btn">
                            <button class="btn btn-success" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                <span style="margin-left:10px;">Search</span>
                            </button>
                        </span>
                        </span>
                    </div>
                    
                </div>
            </div>
            
        </form>
        <!-- End of Search Form -->
            
    </div>
</div>

<?php //echo $this->form()->closeTag(); ?>